apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pwcegbjss-python 
  janus-idp.io/tekton: pwcegbjss-python
  backstage.io/kubernetes-id: pwcegbjss-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pwcegbjss-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  